dist: xenial
sudo: required
language: python

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

before_install:
  - sudo apt-get update
  - sudo apt-get install -y chktex lacheck

install:
  - pip install -r requirements.txt

script:
  - statick . --user-paths statick_config --profile tex-profile.yaml --config tex-config.yaml
